version: '3'

volumes:
  khai_devops:
    driver: local

services:
  postgres:
    container_name: khai_devops_postgres
    image: postgres:15.1
    volumes:
      - khai_devops:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: khai_devops
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"